### ISSUE TITLE
only select this episode

### ISSUE THREAD

**Issue by mortifia** [hama3254/CRD-add-on#3]
crunchyroll beta
on page of an anime

**Comment by Elwador** [comment]
yes same issue 
![image](https://user-images.githubusercontent.com/75888166/183974743-45882480-bf1d-48e4-9d89-12ec50401785.png)
it doesn't show the Select Episodes, Add Episodes and Deselect Button only the Add this Crunchyroll Episode button and this adds the link to the page
and when you start the downloads you have to select the episodes for the link but they never load

**Comment by hama3254** [comment]
Sorry it i did not notice that for a while but it seems like CR obfuscated the class names for the episodes which broke the add-on for the beta website.
![grafik](https://user-images.githubusercontent.com/52826614/188310686-1f04b9d6-166a-4233-9213-fa66b3a63705.png)

[Chrome version 0.6.1 is avalibe](https://github.com/hama3254/CRD-add-on/releases/tag/v0.6.1) Firefox should come soon

**Comment by mortifia** [comment]
thanks to found this :)
on bad connection this help a lot to show in good condition
